### ISSUE TITLE
Running taxi results inconsistent

### ISSUE THREAD

**Issue by mao-ouyang** [rapidsai/spark-examples#59]
I use the taxi-small data, the result of running python spark cpu_main.py and the result of running the modified ETL script again.
The previous figure is the demo data used, and the later is the ETL processed data.
![image](https://user-images.githubusercontent.com/46299753/66571538-0acdce80-eba2-11e9-8df8-45ed256c3a97.png)
![image](https://user-images.githubusercontent.com/46299753/66571366-b0347280-eba1-11e9-9510-49a9a21d9447.png)
Why is this happening?

**Comment by chuanlihao** [comment]
Hi @mao-ouyang,

As far as I understand, two results will be approximate when running with the same dataset and parameters.

I tested with the sample [taxi-small.tar.gz](https://github.com/rapidsai/spark-examples/tree/master/datasets) and the default parameters, the result is ~2.50. (To make it simple, I didn't use the trainWithEval option.) Then I tested again with another [taxi-small-2012-11.zip](https://github.com/rapidsai/spark-examples/files/3716268/taxi-small-2012-11.zip), the result is ~2.65. I made that dataset after fixing [issue 58](https://github.com/rapidsai/spark-examples/issues/58) locally. I think the difference is acceptable because I was testing with two different small datasets.

For your inconsistent issue, please either share your sample datase after ETL, or test again with [taxi-small-2012-11.zip](https://github.com/rapidsai/spark-examples/files/3716268/taxi-small-2012-11.zip). Then we will be able to analyze the results based on the same dataset.

**Comment by anfeng** [comment]
Assuming the issue was resolved per latest suggestion. Feel free to reopen if you still have the problem
